name: Deployment to Staging

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      ecr_repository: appr-tailor-staging
      terraform_directory: terraform/staging
      auth0_custom_domain: cepp-dev.auth0.com
      auth0_domain: cepp-dev.auth0.com
      build_command: npx lerna run build
    secrets:
      auth0_client_id: ${{ secrets.AUTH0_CLIENT_ID_DEV }}
      appr_deploy_access_key: ${{ secrets.APPR_DEPLOY_ACCESS_KEY }}
      appr_deploy_secret_access_key: ${{ secrets.APPR_DEPLOY_SECRET_ACCESS_KEY }}
